### ISSUE TITLE
display_nice_view has nets swapped when reversible is false

### ISSUE THREAD

**Issue by Grazfather** [ceoloide/ergogen-footprints#32]
```yaml
     oled:
         what: ceoloide/display_nice_view
         params:
           VCC: VCC
           MOSI: OLED_MOSI
           CS: OLED_SS
           SCK: OLED_SCK
           include_silkscreen: true
```
<img width="576" alt="Notification_Center" src="https://github.com/ceoloide/ergogen-footprints/assets/497310/e1ba162e-c438-4190-9538-3d8a0f4973ff">

**Comment by hackrmomo** [comment]
The silkscreen legend is correct if I'm not mistaken according to this: 
![image](https://github.com/user-attachments/assets/91baa9d9-800a-45da-b97c-50526b97f848)

You should be able to temporarily circumvent this by doing 
```yaml
params:
  MOSI: CS
  SCK: GND
  VCC: VCC # no actual change needed
  GND: SCK
  CS: MOSI
```
