### ISSUE TITLE
Wrong jumper orientation when `reverse_mount: true` and `reversible: true`

### ISSUE THREAD

**Issue by ceoloide** [ceoloide/ergogen-footprints#45]
When the following configuration is used, the jumpers / vias are not matching the labels and are on the wrong side.

```yaml
pcbs:
  mcu_test:
    template: kicad8
    footprints:
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          reversible: true
          reverse_mount: true
```

The correct orientation should be as follows:
<img width="630" alt="Screenshot 2024-12-03 at 19 20 55" src="https://github.com/user-attachments/assets/16b3d8e7-1092-40f6-84d6-0869d080e0d6">

But this is what one gets with the configuration above:
<img width="436" alt="Screenshot 2024-12-03 at 20 06 38" src="https://github.com/user-attachments/assets/dfb52de4-f5fa-4ba4-9383-cd89b9cde592">
