### ISSUE TITLE
Error opening PCB with switch_choc_v1_v2: "Expected 'end'"

### ISSUE THREAD

**Issue by bentleyjensen** [ceoloide/ergogen-footprints#55]
macOS Sonoma 14.6.1
Tested with KiCad 9.0.1 and 8.0.8

Minimum repro:
```
points:
  zones:
    matrix:
      columns:
        pointer:
      rows:
        home:
outlines:
  primary:
    - what: polygon
      points:
        - ref: matrix_pointer_home
          shift: [18, 18]
        - ref: matrix_pointer_home
          shift: [-18, 18]
        - ref: matrix_pointer_home
          shift: [-18, -18]
        - ref: matrix_pointer_home
          shift: [18, -18]
pcbs:
  primary:
    outlines:
      main:
        outline: primary
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: /^matrix_.*/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"

```

**Steps:**
1. Paste above into [https://ergogen.ceoloide.com/](https://ergogen.ceoloide.com/) and click generate
2. Download `primary.kicad_pcb`
3. Double click to open

**Expected:**
"This file was created with an older version of kicad..."

**Actual:**
"Expected 'end'" error

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/732a3ddc-9399-411a-821e-1db0c117f0d5" />

**Workaround:**
1. Open file in a code editor
2. On lines with `fp_arc`:
    * Replace `fp_arc` with `fp_line`
    * Remove `(mid...)` clause
    * Save and re-open

I was reading through the [KiCad docs](https://dev-docs.kicad.org/en/file-formats/sexpr-intro/index.html#_footprint_arc), and I can't see why it gives an error since it appears to follow the expected format.

I'm happy to put in a PR to fix it if you're happy with switching it to a line.
