### ISSUE TITLE
Alternative net definition for switch_choc_v1_v2 with hotswap or soldered switches

### ISSUE THREAD

**Issue by peterjc** [ceoloide/ergogen-footprints#57]
I'm working on my first keyboard PCB, single-sided choc spacing with the option of hotswap or soldered switches.

I'm trying thee following in Ergogenic v4.1.0,

```yaml
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          include_corner_marks: true
          include_keycap: true
          keycap_height: cy
          keycap_width: cx
          reversible: false
          solder: true
          hotswap: true
          include_traces_vias: false
          choc_v2_support: false
          outer_pad_width_front: 2.0
          outer_pad_width_back: 2.0
```

That gives me trace guides like this in KiCad v9.0.2:

<img width="405" alt="Image" src="https://github.com/user-attachments/assets/387c2022-b1a9-49a8-9814-00ebdbfe2e55" />

That gives me the soldered switch or hotswap option (180 degree rotation), but the net definition means there's a cross over (so need to use both sides):

<img width="405" alt="Image" src="https://github.com/user-attachments/assets/5e26eeb4-8ecc-4701-bbe6-5df18018ea0d" />

I'd rather the net was flipped so the following wiring would be accepted (all on one side):

<img width="405" alt="Image" src="https://github.com/user-attachments/assets/36b5a7e9-6d19-4720-a7cb-62d91c43aea1" />

e.g. as used in https://github.com/OldMan6955/TheEndgame2024 (180 degree rotated compared to the above), screenshot from their KiCad file:

<img width="651" alt="Image" src="https://github.com/user-attachments/assets/22fd7779-8eef-4619-a367-e05b0001052e" />
